version: "3"
services:
  capture:
    image: lblod/docker-network-capture-service
    links:
      - database:database
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
  monitor:
    image: lblod/docker-monitor-service
    links:
      - database:database
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
  database:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
